---
title: "Introducción al control de versiones con Git + GitHub | GitLab"
subtitle: "InnovaLab-Pe"  
author: 
  - "  Antony Barja"
date: '`r Sys.Date()`'
output:
  xaringan::moon_reader:
    css: xaringan-themer.css
    nature:
      slideNumberFormat: "%current%"
      highlightStyle: dark
      highlightLines: true
      ratio: 16:9
      countIncrementalSlides: true
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
knitr::opts_chunk$set(
  fig.width=9, fig.height=6, fig.retina=3,
  out.width = "80%",
  echo = TRUE,
  message = FALSE, 
  warning = FALSE,
  hiline = TRUE
)
```

```{r libraries, include=FALSE}
library(fontawesome)
library(emo)
```

```{r xaringanExtra, echo=FALSE}
# https://github.com/gadenbuie/xaringanExtra
xaringanExtra::use_xaringan_extra("tile_view")
xaringanExtra::use_panelset()
xaringanExtra::use_logo(image_url = "https://avatars.githubusercontent.com/u/46831228?s=200&v=4",
                        width = "120px")
xaringanExtra::use_fit_screen()
xaringanExtra::use_progress_bar(color = "#ee4912", location = "bottom", height = "3px")
```

## Introducción al control de vesiones

---
## Ventajas y limitaciones 


---
## Instalación de Git 


---
## Primeros comandos en Git 


---
## Introducción a GitHub - GitLab


---
## Integración de Git + GitHub



---
## Integración de Git + GitHub


---
## Caso práctico 









